version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my_app_network

  app:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    command: npm start
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge

volumes:
  redis-data: