version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST="redis"
    volumes:
      - redis-data:/data

  app:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm start

volumes:
  redis-data:
